language: C
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=14
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=21

osx_image: xcode8.3

# only works on linux
addons:
  apt:
    packages:
      - python

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew search cppunit ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install cppunit@1.13.1 || brew install cppunit@1.13 ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install gcc48; fi



script:
  - whereis gcc
  - ls -l /usr/bin/*gcc*
  - /usr/bin/gcc --version
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
  - make test
  - pkg-config --version
