language: C
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=14
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=21

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev
      - pkg-config

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew install python flex bison cppunit ; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew ls --versions pkg-config; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew ls --versions azeqsdf; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew outdated azer; fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew outdated pkg-config; fi
# do which [-s ??] package || brew install package

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
  - make test
