language: C
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=14
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=21

osx_image: xcode7.3

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then brew update ; brew install python flex bison cppunit; fi

script:
  - whereis gcc
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
  - make test
  - pkg-config --version
