language: C
compiler:
  - gcc
  - clang
os:
  - linux
  - osx
env:
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=14
  - TEST_ENV_VARIABLE_IN_TRAVIS_YML=21

# only works on linux
addons:
  apt:
    packages:
      - python
      - flex
      - bison
      - libcppunit-dev
      - pkg-config

# need this to install dependencies on osx
before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] ; then
      brew update
      # We add || exit 0 because brew exit with an error if a package is already
      # installed and cannot be updated.
      brew install python flex bison cppunit pkg-confiig || exit 0 #
    fi

script:
  - if [ "$TRAVIS_OS_NAME" = "osx" ] && [ "$CC" = "gcc" ]; then export CC=gcc-4.8; fi
  - make test
