language: cpp
sudo: required

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-4.9
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.9
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-5
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env: COMPILER=g++-6
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - libgmp-dev
          - libgmpxx4ldbl

    - os: osx
      compiler: clang
      env: COMPILER=clang++
      before_install:
      - brew update
      - brew uninstall automake && brew install automake
      - brew install autoconf libtool

install:
  - export CXX="$COMPILER"

script:
  - echo $CC
  - echo $CXX
  - ln -s /usr/bin/gcc
  - ln -s /usr/bin/g++
  - gcc --version
