language: cpp
sudo: required

matrix:
  include:
    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-4.9
        - CC=toto
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-4.9
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-5
        - CC=toto
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-5
          - libgmp-dev
          - libgmpxx4ldbl

    - os: linux
      sudo: required
      dist: trusty
      compiler: gcc
      env:
        - COMPILER=g++-6
        - CC=toto
      addons:
        apt:
          sources:
          - ubuntu-toolchain-r-test
          packages:
          - g++-6
          - libgmp-dev
          - libgmpxx4ldbl

    - os: osx
      compiler: clang
      env:
        - COMPILER=clang++
        - CC=toto
      before_install:
      - brew update
      - brew uninstall automake && brew install automake
      - brew install autoconf libtool

install:
  - export CXX=$CCX${COMPILER_VERSION+:-${COMPILER_VERSION}}
  - export CC=$CC${COMPILER_VERSION+:-${COMPILER_VERSION}}

script:
  - echo $CC
  - echo $CXX
  - ls -l /usr/bin/gcc
  - ls -l /usr/bin/g++
  - gcc --version
  - g++ --version
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/$CCX 90
  - ls -l /usr/bin/gcc
  - ls -l /usr/bin/g++
  - gcc --version
  - g++ --version
